### ISSUE TITLE
Allow many-to-many connections

### ISSUE THREAD

**Issue by debugpoint136** [target2/submissionUI#24]
When adding many-to-many connections, for example in **pooled_from** attribute in biosample, it should allow multiple items to be added

Example - 
```http://target.wustl.edu:8006/api/biosamples/TRGTSMP00010780```

Observed -
<img width="306" alt="screen shot 2017-11-17 at 8 47 26 am" src="https://user-images.githubusercontent.com/2250674/32952846-0c136ee4-cb74-11e7-9e0d-27bad012c47d.png">

Expected - 
<img width="263" alt="screen shot 2017-11-17 at 8 44 46 am" src="https://user-images.githubusercontent.com/2250674/32952852-0e8def0a-cb74-11e7-82ad-dd2eec7ae70c.png">

@xzhuo

**Comment by xzhuo** [comment]
The main issue is solved, but it would be better if we can removed the empty string in list. For example, "biosample": [] instead of "biosample": [""]
